name: sembuhtbc_admin
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  firebase_core: 3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: 5.6.5
  firebase_analytics: ^11.4.4

  # Package untuk memilih gambar dari galeri/kamera
  image_picker: ^1.1.0 # Diupdate ke versi terbaru

  # Package untuk permission handling
  permission_handler: ^10.4.4 # Diupdate ke versi terbaru

  # Package untuk state management
  provider: ^6.1.1

  # Package untuk HTTP requests
  http: ^1.1.0

  # Package untuk shared preferences
  shared_preferences: ^2.2.2

  # Package untuk validasi form
  form_field_validator: ^1.1.0

  # Package tambahan untuk kompatibilitas
  flutter_plugin_android_lifecycle: ^2.0.7 # Ditambahkan untuk mendukung lifecycle

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    # Roboto Font
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

    # Urbanist Font
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Regular.ttf
        - asset: fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: fonts/Urbanist-Bold.ttf
          weight: 700

    # Montserrat Font
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/images/calendar_icon.png
    - assets/images/welcome_scr.png
    - assets/images/avatar.png
